<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
    <PackageReference Include="bunit" Version="2.11.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProgressHomeHeating.Web\ProgressHomeHeating.Web.csproj" />
    <ProjectReference Include="..\ProgressHomeHeating.Contracts\ProgressHomeHeating.Contracts.csproj" />
  </ItemGroup>

</Project>
