[consent]
notice_shown = true
notice_shown_date = "2026-08-31T13:14:50.464979+00:00"
notice_shown_by = "nia"
consented = true
opted_out = false
consent_date = "2026-08-31T13:14:50.464979700+00:00"
consent_phrase = "i agree"
consented_by = "nia"
